#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  brew install git
  cd ~
  git clone https://github.com/highspeedmp/dotfiles.git

  rm -rf ~/.Brewfile
  ln -s ~/dotfiles/.Brewfile ~/.Brewfile

  rm -rf ~/.inputrc
  ln -s ~/dotfiles/.inputrc ~/.inputrc

  rm -rf ~/.iterm2
  ln -s ~/dotfiles/.iterm2 ~/.iterm2

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
  fi
fi

if [ "$system_type" = "Linux" ]; then

  apt install -y git
  cd ~
  git clone https://github.com/highspeedmp/dotfiles.git

  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
  curl -L https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
  sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
  echo 'deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu xenial main' > /etc/apt/sources.list
  apt-key adv --keyserver pgp.mit.edu --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
  add-apt-repository multiverse
  apt update
  apt install -y google-chrome-stable atom dropbox python-gpgme steam
fi


# Shared config

rm -rf ~/.ssh/config
ln -s ~/dotfiles/.ssh-config ~/.ssh/config

rm -rf ~/.bashrc
ln -s ~/dotfiles/.bashrc ~/.bashrc

rm -rf ~/.vimrc
ln -s ~/dotfiles/.vimrc ~/.vimrc

rm -rf ~/.tmux.conf
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf

if command -v vim >/dev/null 2>&1; then
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
